export const filterSectionFilters = [
  { name: 'TransactionId', statisticalType: 'Data - Categorical - free form' },
  { name: 'InvoiceNumber', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'TotalDonorPayments', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'InvoiceAmount', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'MemberPaidAmount', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'TransactionDonationAmount', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'TransactionPcp', statisticalType: 'Data - Categorical - free form' },
  { name: 'TransactionAmount', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'TransactionDate', statisticalType: 'Data - Numeric - Temporal' },
  { name: 'InvoiceId', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'TransactionDonor', statisticalType: 'Data - Categorical - free form' },
  { name: 'TransactionMember', statisticalType: 'Data - Categorical - free form' },
  { name: 'MemberAmountPaid', statisticalType: 'Data - Numeric - NTG - Discrete' },
];
