export const filterSectionFilters = [
  { name: 'DonorId', statisticalType: 'Data - Categorical - free form' },
  { name: 'DonorCommitment', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'DonorFax', statisticalType: 'Data - Categorical - unordered' },
  { name: 'DonorSpentYtd', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'DonorZip', statisticalType: 'Data - Categorical - unordered - geo' },
  { name: 'DonorCurrentBalance', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'MinPerTransaction', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'DonorSuite', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'DonorStreetAddress', statisticalType: 'Data - Categorical - free form' },
  { name: 'PaidMembers', statisticalType: 'Data - Categorical - free form' },
  { name: 'DonorName', statisticalType: 'Data - Categorical - free form' },
  { name: 'MaxPerTransaction', statisticalType: 'Data - Numeric - NTG - Discrete' },
  { name: 'DonorPhoneNumber', statisticalType: 'Data - Categorical - unordered' },
  { name: 'BusinessName', statisticalType: 'Data - Categorical - free form' },
  { name: 'PreferredMember', statisticalType: 'Data - Categorical - free form' },
];
