export enum WidgetCategory {
  Table = 'table',
  Summary = 'summary',
  Visualization = 'visualization',
}

export enum WidgetIcons {
  Action = 'ks-action',
  Config = 'ks-config',
  Custom = 'ks-custom',
  Summary = 'ks-summary-details',
  Table = 'ks-table',
  Visualization = 'ks-visualization',
}

export enum WidgetSection {
  Investigation = 'investigation',
  MainSection = 'main-section ',
  Preview = 'preview',
}

export enum WidgetScope {
  Collection = 'collection',
  Single = 'single',
}

export enum WidgetTypes {
  AREA = '[WIDGET] AREA',
  AREA_GRADIENT = '[WIDGET] AREA_GRADIENT',
  AREA_MACRO_MICRO = '[WIDGET] AREA_MACRO_MICRO',
  AREA_MASTER_DETAIL = '[WIDGET] AREA_MASTER_DETAIL',
  AREA_TREND = '[WIDGET] AREA_TREND',
  BUBBLE_CHART = '[WIDGET] BUBBLE_CHART',
  COLUMN_BAR = '[WIDGET] COLUMN_BAR',
  COLUMN_BAR_DOUBLE_BAR = '[WIDGET] COLUMN_BAR_DOUBLE_BAR',
  COLUMN_BAR_MACRO_MICRO = '[WIDGET] COLUMN_BAR_MACRO_MICRO',
  COLUMN_BAR_SEGMENTED = '[WIDGET] COLUMN_BAR_SEGMENTED',
  CONFIG_INPUT_FIELD_USER_DEFINED = '[WIDGET] CONFIG_INPUT_FIELD_USER DEFINED',
  CONFIG_TABLE = '[WIDGET] CONFIG_TABLE',
  CUSTOM = '[WIDGET] CUSTOM',
  CUSTOM_ACTION = '[WIDGET] CUSTOM_ACTION',
  DONUT = '[WIDGET] DONUT',
  DONUT_VARIANT = '[WIDGET] DONUT_VARIANT',
  FULL_TABLE = '[WIDGET] FULL_TABLE',
  GAUGE = '[WIDGET] GAUGE',
  GAUGE_SEVERITY_LEVEL = '[WIDGET] GAUGE_SEVERITY_LEVEL',
  GAUGE_SEVERITY_SCORE = '[WIDGET] GAUGE_SEVERITY_SCORE',
  LINE = '[WIDGET] LINE',
  PIE = '[WIDGET] PIE',
  POLAR_AREA = '[WIDGET] POLAR_AREA',
  POSITIVE_NEGATIVE_AREA = '[WIDGET] POSITIVE_NEGATIVE_AREA',
  READ_ONLY_TEXT = '[WIDGET] READ_ONLY_TEXT',
  SCATTER = '[WIDGET] SCATTER',
  SIMPLE_LIST = '[WIDGET] SIMPLE_LIST',
  SIMPLE_LIST_RANKED = '[WIDGET] SIMPLE_LIST_RANKED',
  SINGLE_BAR_HIGHLIGHT_MAX = '[WIDGET] SINGLE_BAR_HIGHLIGHT_MAX',
  STEP_LINE = '[WIDGET] STEP_LINE',
  SUMMARY = '[WIDGET] SUMMARY',
  SUMMARY_SLOT = '[WIDGET] SLOT',
  SUMMARY_STATISTICS = '[WIDGET] SUMMARY_STATISTICS',
  TABLE = '[WIDGET] TABLE',
  WATERFALL = '[WIDGET] WATERFALL',
}
