/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:2bad289b-d62e-48a6-8166-7683aa3f44af',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_VR2VKgPcz',
  aws_user_pools_web_client_id: '1p4er3n6p6kngrpfvblb1smq2u',
  oauth: {},
  aws_cognito_login_mechanisms: ['PHONE_NUMBER'],
  aws_cognito_signup_attributes: ['PHONE_NUMBER'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_verification_mechanisms: ['PHONE_NUMBER'],
};

export default awsmobile;
