import customIcons from './custom';
import generatedIcons from './generated';

export default {
  'ks-action': { path: './assets/icons/icon-action.svg', alt: 'Action' },
  'ks-add': { path: './assets/icons/add.svg', alt: 'Add' },
  'ks-card-selector': { path: './assets/icons/icon-card-selector.svg', alt: 'Selector' },
  'ks-close': { path: './assets/icons/close.svg', alt: 'Close' },
  'ks-config': { path: './assets/icons/icon-config.svg', alt: 'Config' },
  'ks-custom': { path: './assets/icons/icon-custom.svg', alt: 'Custom' },
  'ks-date-picker': { path: './assets/icons/calendar-3.svg', alt: 'Date Picker' },
  'ks-delete': { path: './assets/icons/bin-1.svg', alt: 'Delete' },
  'ks-edit': { path: './assets/icons/pencil.svg', alt: 'Edit' },
  'ks-end-user': { path: './assets/icons/single-neutral-circle.svg', alt: 'End User' },
  'ks-entity': { path: './assets/icons/module.svg', alt: 'Entity' },
  'ks-expand': { path: './assets/icons/expand-diagonal-2.svg', alt: 'Expand' },
  'ks-filter': { path: './assets/icons/filter-1.svg', alt: 'Filter' },
  'ks-granularity': { path: './assets/icons/granularity.svg', alt: 'Granularity' },
  'ks-help': { path: './assets/icons/question-help-circle.svg', alt: 'Help' },
  'ks-home': { path: './assets/icons/home.svg', alt: 'Home' },
  'ks-logout': { path: './assets/icons/logout-2.svg', alt: 'Logout' },
  'ks-menu': { path: './assets/icons/navigation-menu.svg', alt: 'Menu' },
  'ks-navigation-menu-vertical': {
    path: './assets/icons/navigation-menu-vertical.svg',
    alt: 'Navigation menu vertical',
  },
  'ks-page': { path: './assets/icons/notes-paper.svg', alt: 'Sort Desc' },
  'ks-preferences': { path: './assets/icons/cog.svg', alt: 'Preferences' },
  'ks-robot': { path: './assets/icons/robot.svg', alt: 'Error Robot' },
  'ks-sort-asc': { path: './assets/icons/arrange-letter.svg', alt: 'Sort Asc' },
  'ks-sort-desc': { path: './assets/icons/arrange-letter-desc.svg', alt: 'Sort Desc' },
  'ks-summary-details': { path: './assets/icons/icon-summaryDetails.svg', alt: 'Summary' },
  'ks-table': { path: './assets/icons/icon-table.svg', alt: 'Table' },
  'ks-user': { path: './assets/icons/user.svg', alt: 'User' },
  'ks-visualization': { path: './assets/icons/icon-visualization.svg', alt: 'Visualization' },
  'sort-asc': { path: './assets/icons/arrange-letter.svg', alt: 'Sort Asc' },
  'sort-desc': { path: './assets/icons/arrange-letter-desc.svg', alt: 'Sort Desc' },
  ...generatedIcons,
  ...customIcons,
};
